### PR TITLE
Get the tests passing.

### PR DESCRIPTION
**Pull request by jenkoian**
* Get tests running
* Add new Picsum provider due to slow Image provider causing issues with
  tests. It seems LoremPixel is really slow and unreliable.

### CODE REVIEW

**Comment by jenkoian** [comment]
Once this is merged I can look at getting travis set up ?

**Comment by nlemoine** [comment]
Thanks for making the tests passing again.

> Add new Picsum provider due to slow Image provider causing issues with
tests. It seems LoremPixel is really slow and unreliable.

I noticed that too and already have a provider I never push on this remote repository. I'll probably rewrite some part of it to make slightly shorter.

**Comment by nlemoine** [comment]
@jenkoian I merged your PR and made some changes. Travis is up again.

**Comment by jenkoian** [comment]
Top stuff @nlemoine 👍

**Pull request merged**
